name: coin_base
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  iconify_flutter_plus: ^1.0.4
  font_awesome_flutter: ^10.8.0
  get: ^4.3.8 
  pocketbase: ^0.21.0
  flutter_local_notifications: ^18.0.1
  sign_in_button: ^3.2.0
  google_fonts: ^4.0.4
#  firebase_core: ^3.10.1
  url_launcher: ^6.3.1
  intl: ^0.20.2
  html: ^0.15.5
  
#  firebase_auth: ^5.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
